Detailr.MVC/Views/Shared/Components/BusinessChoiceTagsSelect/BusinessChoiceTagsSelectViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.BusinessChoiceTagsSelect
{
    public class BusinessChoiceTagsSelectViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/BusinessRadioSelect/BusinessRadioSelectViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.RadioSelect
{
    public class BusinessRadioSelectViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/BusinessRadiusSelect/BusinessRadiusSelectViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.RadiusSelect
{
    public class BusinessRadiusSelectViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/BusinessSearch/BusinessSearchViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.BusinessSearch
{
    public class BusinessSearchViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/BusinessSearchSummary/BusinessSearchSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.BusinessSearchSummary
{
    public class BusinessSearchSummaryViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/BusinessSearchUserDetails/BusinessSearchUserDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.BusinessSearchUserDetails
{
    public class BusinessSearchUserDetailsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/Logo/LogoViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.Logo
{
    public class LogoViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/Components/Navbar/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Detailr.MVC.Views.Shared.Components.Navbar
{
    public class NavbarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Detailr.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Detailr.MVC</title>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>document.getElementsByTagName("html")[0].className += " js";</script>
    <link rel="stylesheet" href="https://unpkg.com/codyhouse-framework/main/assets/css/style.min.css">
    <script src="https://unpkg.com/codyhouse-framework/main/assets/js/util.js"></script>
    <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>

    <link rel="stylesheet" href="~/css/Navbar.css" />
    <link rel="stylesheet" href="~/css/AnimatedMenuButton.css" />

</head>
<body>

    @if (TempData["hideNav"] != "hide") {
        @await (Component.InvokeAsync("Navbar"));
    }


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - Detailr.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@

    <script src="~/js/AnimatedMenuButton.js"></script>
    <script src="~/js/Collapse.js"></script>
    <script src="~/js/Navbar.js"></script>
    
</body>
</html>